runtime: go
api_version: go1

handlers:
#- url: /(.*\.(gif|png|jpg))$
#  static_files: static/\1
#  upload: static/.*\.(gif|png|jpg)$

- url: /assets
  static_dir: assets

- url: /bower_components/(.*\.(js|html|css|gif|png|jpg|svg))$
  static_files: bower_components/\1
  upload: bower_components/.*\.(js|html|css|gif|png|jpg|svg)$

- url: /views
  static_dir: views

- url: /.*
  script: _go_app